version: '2'

services:
  django:
    build: .
    image: weatherapp
    command: gunicorn core.wsgi -b 0.0.0.0:8000 -w 1
    env_file:
      - .env
    ports:
      - "127.0.0.0:8001:8000"

  bot:
    build: .
    image: weatherapp
    command: python bot/main.py
    env_file:
      - .env
